version: '3.3'
services:
  api:
    image: delivery-much-test
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"

  web-cli:
    image: delivery-much-test
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
